# Generated by Django 3.2.4 on 2021-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('order_number', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('keyword', models.CharField(max_length=20)),
                ('qr_code', models.ImageField(upload_to='qr_codes/')),
            ],
            options={
                'ordering': ('-order_number',),
            },
        ),
    ]
