# Generated by Django 3.2.4 on 2021-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'ordering': ('-order_number',), 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='videos',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
