# Generated by Django 3.2.4 on 2021-07-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210710_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
